<h2 style="color:orange;font-size:30px;">Variables</h2>
#We use variables to temporarily store data in computer’s memory.

In [115]:
print("my name is nirmal")

my name is nirmal


In [118]:
var1 = 15156
type(var1)

int

In [29]:
log1 = True
type(log1)

bool

In [1]:
char1 = "nirmal"
type(char1)

str

In [5]:
comp1 = 3+5j

In [6]:
type(comp1)

complex

In [7]:
fol=12.56526
type(fol)

float

In [ ]:
#oprators

In [ ]:
#Arithmatic oprators +,-,*,/

In [2]:
n1 = 40
n2 = 60

In [119]:
#Addition
n1 + n2

100

In [3]:
#subtraction
n2 - n1

20

In [4]:
n1 - - n2

100

In [11]:
#multiplication

n1 * n2 #Multiplying two integers results in an int, and multiplying a number with a float results in a float.

2400

In [5]:
2 * 8.0

16.0

In [12]:
#division
n2 / n1 #division with the / operator always returns a float.

1.5

In [6]:
#integer division
9//3

3

In [7]:
5 // 2

2

In [8]:
-3 // 2 #First, -3 is divided by 2 to get -1.5. Then -1.5 is rounded down to -2.

-2

In [9]:
#Exponents

2 ** 2

4

In [10]:
2**6

64

In [12]:
9**0.5

3.0

In [13]:
#Modulus (returns the remainder of dividing)

5 % 3

2

In [14]:
20%7

6

In [15]:
16%8

0

In [16]:
5%-3 # r = x - (y * (x // y)).

-1

In [17]:
#Arithmetic Expressions
2*3-1 #6-1 = 5

5

In [18]:
4/2 + 2**3 #2 + 8 = 10

10.0

In [19]:
-1 + (-3*2 + 4) #-1 + (-6+4) => -1+(-2) = -3

-3

#Math Functions and Number Methods
- round(), for rounding numbers to some number of decimal places
- abs(), for getting the absolute value of a number
- pow(), for raising a number to some power

In [23]:
# round
round(5.5)

6

In [24]:
round(2.3)

2

In [25]:
round(5.15145151, 4)

5.1515

In [26]:
#abs
abs(3)

3

In [27]:
abs(-5.0)

5.0

In [28]:
#pow Power
pow(2, -2)

0.25

In [29]:
pow(4,2)

16

In [30]:
num = 2.5
num.is_integer()

False

In [31]:
num = 2.0
num.is_integer()

True

In [32]:
#Print Numbers in Style

x1 = 5

f"The value of x1 is: {x1}"

'The value of x1 is: 5'

In [34]:
x2 = 5.4656464

f"The value of x2 is: {x2:.2f}"

'The value of x2 is: 5.47'

In [35]:
x3 = 1

f"The value of x2 is: {x3:.2f}"

'The value of x2 is: 1.00'

In [36]:
x4 = 15221656265652652564
f"The value of x2 is: {x4:,}"

'The value of x2 is: 15,221,656,265,652,652,564'

In [37]:
x5 = 65562665695.52525
f"The value of x2 is: {x5:,.2f}"

'The value of x2 is: 65,562,665,695.53'

In [38]:
balance = 2000.0
spent = 256.32
remaining = balance - spent

f"After spending ${spent:.2f}, I was left with ${remaining:.2f}"

'After spending $256.32, I was left with $1743.68'

In [49]:
#complex number
c1 = 1+2j

In [50]:
c1.real

1.0

In [51]:
c1.imag

2.0

In [52]:
c1.conjugate()

(1-2j)

In [53]:
c2 = 1 +2j
c3 = 3-4j

In [54]:
c2+c3

(4-2j)

In [55]:
c2-c3

(-2+6j)

In [56]:
c2*c3

(11+2j)

In [ ]:
#relational oprators - <, >, ==, !=

In [13]:
n1, n2

(40, 60)

In [121]:
n1 < n2

True

In [15]:
n1 > n2

False

In [16]:
n1 == n2

False

In [17]:
n1 != n2

True

In [18]:
#logical oprator - &, |

In [19]:
l1 = True
l2 = False

In [20]:
l1 & l2

False

In [21]:
l2 & l1

False

In [22]:
l1 & l1

True

In [23]:
l2 & l2

False

In [24]:
l1 | l2

True

In [25]:
l2 | l1

True

In [26]:
l1 | l1

True

In [27]:
l2 | l2

False

In [28]:
#string

In [4]:
str3 = '''hi nanthini how are you i am good nirmal'''
str3

'hi nanthini how are you i am good nirmal'

In [1]:
str4 = "This is my first python program"
len(str4)

31

<h2 style="color:orange;font-size:30px;">String Slicing</h2>

In [3]:
str4 = "This is my first python program"

In [6]:
str4[0]

'T'

In [7]:
str4[-1]

'm'

In [8]:
str4[2:5]

'is '

In [10]:
str4[1:10:2]

'hsi y'

In [4]:
str4[:]

'This is my first python program'

In [12]:
str4[5:]

'is my first python program'

In [13]:
str4[:5]

'This '

In [5]:
str4[:-5]

'This is my first python pr'

In [6]:
str4[-5:]

'ogram'

In [14]:
str4[::-1]

'margorp nohtyp tsrif ym si sihT'

In [15]:
str4[-1:-2]

''

In [16]:
str4[-2:-1]

'a'

In [18]:
str4[:-1:2]

'Ti sm is yhnpor'

In [33]:
word = "goal"
word = "f" + word[0:]
print(word)

fgoal


In [34]:
word = "goal"
word = "f" + word[1:]
print(word)

foal


In [37]:
#Manipulate Strings With Methods

In [38]:
str4.lower()

'this is my first python program'

In [39]:
str4.upper()

'THIS IS MY FIRST PYTHON PROGRAM'

In [27]:
str4.capitalize()

'This is my first python program'

In [28]:
str4.title()

'This Is My First Python Program'

In [21]:
str4.replace("first", "1st")

'This is my 1st python program'

In [22]:
str4.split()

['This', 'is', 'my', 'first', 'python', 'program']

In [24]:
str5 = "      I love data analytics     "
str5.strip()

'I love data analytics'

In [25]:
str5.lstrip()

'I love data analytics     '

In [26]:
str5.rstrip()

'      I love data analytics'

In [42]:
str6 = "I love cricket"
str6.startswith("I love")

True

In [43]:
str6.endswith("et")

True

In [46]:
str6.startswith("i")

False

In [47]:
str6.endswith("a")

False

In [49]:
msg = "Hay what's up? "
user_input = input(msg)
print("You said:", user_input)

Hay what's up? Good buddy
You said: Good buddy


In [50]:
#Strings and Arithmetic Operators
num = "2"
num + num

'22'

In [51]:
num  * 5

'22222'

In [52]:
num = input("Enter a number to be doubled: ")
doubled_num = num * 2
print(doubled_num)

Enter a number to be doubled: 5
55


In [54]:
#Converting Strings to Numbers
int("55")

55

In [55]:
float("55")

55.0

In [58]:
int("12.0")

ValueError: invalid literal for int() with base 10: '12.0'

In [59]:
#Converting Numbers to Strings
cupcakes = 10
"I am going to eat " + str(cupcakes) + " cupcakes"

'I am going to eat 10 cupcakes'

In [60]:
cupcakes = 10
"I am going to eat " + str(10) + " cupcakes"

'I am going to eat 10 cupcakes'

In [62]:
total_cupcakes = 10
cupcakes_eaten = 5

"Only " + str(total_cupcakes - cupcakes_eaten) + " cupcakes left."

'Only 5 cupcakes left.'

In [68]:
name = "Nirmal kumar"
place = "Kumbakonam"
age = "27"
dgree = "B.E(ECE)"

f"My self {name}, i am from {place}, my age is {age}, i have completd {dgree}."

'My self Nirmal kumar, i am from Kumbakonam, my age is 27, i have completd B.E(ECE).'

In [64]:
n = 3
m = 4
f"{n} times {m} is {n*m}"

'3 times 4 is 12'

In [71]:
newstring = 'nirmal is good boy is good person good solemate good chrater'

In [73]:
newstring.count("good")

4

In [53]:
# find index

In [54]:
newstring.find('solemate')

39

In [55]:
course = 'i have complete course, XML, Sql, html, pyrhon, tableau, powerBi, excel'

In [56]:
course.split(',')

['i have complete course',
 ' XML',
 ' Sql',
 ' html',
 ' pyrhon',
 ' tableau',
 ' powerBi',
 ' excel']

<h2 style="color:red;font-size:30px;">List</h2>


1. Lists are used to store multiple items in a single variable.
2. Lists are created using square brackets
3. List items are ordered, changeable, and allow duplicate values.
4. Lists are one of 4 built-in data types in Python used to store collections of data

l1 =[1,'a',2,'b',3,'c']

In [3]:
type(l1)

list

In [4]:
l1[3]

'b'

In [5]:
l1[0:3]

[1, 'a', 2]

In [6]:
l1[:]

[1, 'a', 2, 'b', 3, 'c']

In [7]:
l1[3:]

['b', 3, 'c']

In [8]:
l1[:4]

[1, 'a', 2, 'b']

In [9]:
l1[::-1] #list reverse

['c', 3, 'b', 2, 'a', 1]

In [12]:
l1[-1:]

['c']

In [13]:
l1[:-1]

[1, 'a', 2, 'b', 3]

In [14]:
l1[:5:2]

[1, 2, 3]

In [11]:
l1[1:-2]

['a', 2, 'b']

In [26]:
# Check existence of an element
2 in l1

True

In [29]:
"d" in l1

False

In [16]:
lst =[4, 5, "nirmal", 555.5, "python", "data analytics"]
lst

[4, 5, 'nirmal', 555.5, 'python', 'data analytics']

In [18]:
lst.append("tableau") #Insert the value x at the end of the list
lst

[4, 5, 'nirmal', 555.5, 'python', 'data analytics', 'tableau', 'tableau']

In [19]:
lst.pop() #Remove and return the element at index i

'tableau'

In [20]:
lst.reverse()
lst

['tableau', 'data analytics', 'python', 555.5, 'nirmal', 5, 4]

In [21]:
lst.insert(3, "Machine learning") #Insert the value x at index i
lst

['tableau',
 'data analytics',
 'python',
 'Machine learning',
 555.5,
 'nirmal',
 5,
 4]

In [36]:
lst.insert(len(lst), "power bi")
lst

['Machine learning',
 'data analytics',
 'python',
 'tableau',
 555.5,
 'nirmal',
 5,
 4,
 'power bi',
 'power bi']

In [37]:
lst.extend(["sas", "excel", "R"]) #Insert all the values of iterable at the end of the list, in order
lst

['Machine learning',
 'data analytics',
 'python',
 'tableau',
 555.5,
 'nirmal',
 5,
 4,
 'power bi',
 'power bi',
 'sas',
 'excel',
 'R']

In [38]:
lst.pop(-4)
lst

['Machine learning',
 'data analytics',
 'python',
 'tableau',
 555.5,
 'nirmal',
 5,
 4,
 'power bi',
 'sas',
 'excel',
 'R']

In [24]:
lst2 = ["nirmal", "kumar", "nanthini", "vicky", "manoj", "ajith"]
lst2.sort()
lst2

['ajith', 'kumar', 'manoj', 'nanthini', 'nirmal', 'vicky']

In [ ]:
#concatenating list

In [1]:
l1 = [1,2,3]
l2 = [4,5,6,]

In [81]:
l1+l2

[1, 2, 3, 4, 5, 6]

In [82]:
l2+l1

[4, 5, 6, 1, 2, 3]

In [2]:
l1.append(l2)
print(l1)

[1, 2, 3, [4, 5, 6]]


In [3]:
l1[7]

IndexError: list index out of range

In [83]:
#repeat a list

In [84]:
l2*3

[4, 5, 6, 4, 5, 6, 4, 5, 6]

In [34]:
# Print only the odd numbers in the list
l3 = [1,2,3,4,5,6,7,8,9,10]

for i in l3:
    if i%2!=0:
        print(i)

1
3
5
7
9


In [42]:
nums = [1,2,3,4,5,6]
total = 0

for i in nums:
    total = total + i
print(total)

21


In [43]:
sum([1,2,3,4,5,6])

21

In [45]:
min(nums)

1

In [46]:
max(nums)

6

In [48]:
#List Comprehensions

l5 = [2,4,6,7,3,6]
squares = [i**2 for i in l5]
squares

[4, 16, 36, 49, 9, 36]

In [49]:
squares = []

for i in l5:
    squares.append(i**2)
print(squares)

[4, 16, 36, 49, 9, 36]


In [ ]:
#Tuple ()

In [88]:
t1 = (1,'a',True,2,'b',False)

In [89]:
type(t1)

tuple

In [90]:
t1[2]

True

In [91]:
t1[2:5]

(True, 2, 'b')

In [92]:
len(t1)

6

In [93]:
t2 = (33, "nanthini")
t3 = (35, "nirmal")

In [94]:
t2+t3

(33, 'nanthini', 35, 'nirmal')

In [95]:
t2*3

(33, 'nanthini', 33, 'nanthini', 33, 'nanthini')

In [97]:
t2*2+t3

(33, 'nanthini', 33, 'nanthini', 35, 'nirmal')

In [98]:
t4 = (55,66,64,84,94,75,51)

In [99]:
min(t4)

51

In [100]:
max(t4)

94

In [ ]:
#dictionary {}

In [101]:
no = {"nanthini":33, "nirmal":35, "palani":38, "kavi":40}

In [103]:
type(no)

dict

In [104]:
no.keys()

dict_keys(['nanthini', 'nirmal', 'palani', 'kavi'])

In [106]:
no.values()

dict_values([33, 35, 38, 40])

In [108]:
no["vicky"]=60
no

{'nanthini': 33, 'nirmal': 35, 'palani': 38, 'kavi': 40, 'vicky': 60}

In [109]:
no["kavi"]=20
no

{'nanthini': 33, 'nirmal': 35, 'palani': 38, 'kavi': 20, 'vicky': 60}

In [111]:
no1 = {"nanthini":33, "nirmal":35}
no2 = {"naveen":15, "kumar":40}

In [114]:
no1.update(no2)
no1

{'nanthini': 33, 'nirmal': 35, 'naveen': 15, 'kumar': 40}

In [148]:
no1.pop('nirmal')

35

In [149]:
#set

In [154]:
s1 ={1,2,3,4,5}

In [155]:
s1.add(6)
s1

{1, 2, 3, 4, 5, 6}

In [156]:
s1.remove(4)
s1

{1, 2, 3, 5, 6}

In [171]:
s2 = {1,2,3,4,5,6,7}
s3 = {5,6,7,8}

In [170]:
s2.union(s3)

{1, 2, 3, 4, 5, 6, 7, 8}

In [172]:
s2.intersection(s3)

{5, 6, 7}

In [ ]:
#if

In [11]:
a = 50
b = 60

In [13]:
if b>a:
    print("not valid")

not valid


In [15]:
if a<b:
    print("valid")

valid


In [16]:
if a<b:
    print("valid")
else:
    print("not valid")

valid


In [17]:
#elif

In [18]:
a = 100
b = 50
c = 150

In [19]:
if (a>b) & (a>c):
    print("a is maximum")
if (b>a) & (b>c):
    print("b is maximum")
else:
    print("c is maximum")

c is maximum


In [ ]:
#tuple with if

In [20]:
tup1 = ("nirmal", "nanthini", "kumar", "puvi") 

In [23]:
if "nanthini" in tup1:
    print("present in tup1")
else:
    print("not present")

present in tup1


In [ ]:
#list with if

In [24]:
l1 = [10,20,30,40]

In [25]:
if l1[1]==20:
    l1[1]=50

In [26]:
l1

[10, 50, 30, 40]

In [ ]:
#dictionary with if

In [30]:
d1 ={"a1":10,"a2":20,"a3":30,"a4":40,}

In [31]:
if d1["a3"]==30:
    d1["a3"]=d1["a3"]+300
d1

{'a1': 10, 'a2': 20, 'a3': 330, 'a4': 40}

In [ ]:
#looping statement - for,while,repeating,each

In [4]:
for letter in "Python":
    print(letter)

P
y
t
h
o
n


In [7]:
word = "Python"
index = 0

while index < len(word):
    print(word[index])
    index = index + 1

P
y
t
h
o
n


In [8]:
for n in range(3):
    print("Pyhon")

Pyhon
Pyhon
Pyhon


In [9]:
for n in range(10, 20):
    print(n * n)

100
121
144
169
196
225
256
289
324
361


In [34]:
a1 = ["nirmal", "kumar", "nanthini"]

In [36]:
for i in a1:
    print(i)


nirmal
kumar
nanthini


In [39]:
fruits =["apple", "mango", "gova", "graph"]
color =["red", "yellow", "green", "blue"]

In [41]:
for f in fruits:
    for c in color:
        print(f,c)

apple red
apple yellow
apple green
apple blue
mango red
mango yellow
mango green
mango blue
gova red
gova yellow
gova green
gova blue
graph red
graph yellow
graph green
graph blue


In [ ]:
#while loop

In [1]:
n = 1
while n < 5:
    print(n)
    n = n + 1

1
2
3
4


In [3]:
num = float(input("Enter postive number: "))

while num <=0:
    print("that's not a positive number!")
    num = float(input("Enter postive number: "))

Enter postive number: -1
that's not a positive number!
Enter postive number: 6


In [1]:
i=1
n=2
while i<=10:
    print(n," * ",i," = ",n*i)
    i=i+1

2  *  1  =  2
2  *  2  =  4
2  *  3  =  6
2  *  4  =  8
2  *  5  =  10
2  *  6  =  12
2  *  7  =  14
2  *  8  =  16
2  *  9  =  18
2  *  10  =  20


In [11]:
l1 = [1,2,3,4,5]

In [12]:
i=0
while i<len(l1):
    l1[i]=l1[i]+100
    i=i+1

In [13]:
l1

[101, 102, 103, 104, 105]

In [62]:
# Function 
def multiply(x,y):
    product = x*y
    return product

num = multiply(5,6)
print(f"The answer is: {num}")

The answer is: 30


In [65]:
#Functions With No Return Statement
def greet(name):
    print(f"Hello, {name}!")
greet("Nirmal")

Hello, Nirmal!


In [14]:
#Object

In [28]:
class phone:
    def set_color(self,color):
        self.color=color
    def set_cost(self,cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost

In [29]:
ph1 = phone()

In [18]:
ph1.mob_number()

9655311987


In [19]:
ph1.mob_brand()

MI


In [33]:
ph1.set_color("red")

In [34]:
ph1.set_cost(9999)

In [35]:
ph1.show_color()

'red'

In [36]:
ph1.show_cost()

9999

In [ ]:
#constructors

In [42]:
class employee:
    def __init__(self,name,age,salary,gender):
        self.name = name
        self.age = age
        self.salary = salary
        self.gender = gender
    def show_employee_details(self):
        print("Name of the employee is",self.name)
        print("age of the employee is",self.age)
        print("salary of the employee is",self.salary)
        print("gender of the employee is",self.gender)

In [43]:
emp1 = employee("nirmal",25,15000,"Male")

In [44]:
emp1.show_employee_details()

Name of the employee is nirmal
age of the employee is 25
salary of the employee is 15000
gender of the employee is Male


In [ ]:
#inheritance 

In [49]:
class vehicle:
    def __init__(self,cost,mileage):
        self.cost = cost
        self.mileage = mileage
    def show_vehicle_details(self):
        print("i am a vehicle")
        print("cost of the vehicle is",self.cost)
        print("mileage of the vehicle is",self.mileage)
    

In [52]:
v1 = vehicle(200000,150)

In [53]:
v1.show_vehicle_details()

i am a vehicle
cost of the vehicle is 200000
mileage of the vehicle is 150


In [56]:
class car(vehicle):
    def show_car(self):
        print("i am a car")

In [57]:
c1 = car(450000,150)

In [58]:
c1.show_vehicle_details()

i am a vehicle
cost of the vehicle is 450000
mileage of the vehicle is 150


In [59]:
c1.show_car()

i am a car


In [83]:
class vehicle():
    def __init__(self,mileage,cost):
        self.mileage = mileage
        self.cost = cost
    def show_vehicle_detials(self):
        print("i am a vehicle")
        print("mileage of the vehicle is",slef.mileage)
        print("cost of the vehicle is",self.cost)

In [78]:
c1.show_car_details()

i am a car
the number of tyres are 4
the horse of power is 200


In [ ]:
#multiple inheritance

In [96]:
class parent1():
    def assign_str_one(self,str1):
        self.str1 = str1
    def show_str_one(self):
        return self.str1

In [106]:
class parent2():
    def assign_str_two(self,str2):
        self.str2 = str2
    def show_str_two(self):
        return self.str2

In [107]:
class child(parent1,parent2):
    def assign_str_three(self,str3):
        self.str3 = str3
    def show_str_three(self):
        return self.str3

In [108]:
c1=child()

In [109]:
c1.assign_str_one("one")

In [110]:
c1.assign_str_two("two")

In [111]:
c1.assign_str_three("three")

In [103]:
c1.show_str_one()

'one'

In [112]:
c1.show_str_two()

'two'

In [113]:
c1.show_str_three()

'three'

In [164]:
class parent():
    def assign_name(self,name):
        self.name = name
    def show_name(self):
        return self.name

In [165]:
class Child(parent):
    def assign_age(self,age):
        self.age = age
    def show_age(self):
        return self.age

In [166]:
class GrandChild(Child):
    def assign_gender(self,gender):
        self.gender = gender
    def show_gender(self):
        return self.gender

In [167]:
gc = GrandChild()

In [168]:
gc.assign_name("nirmal")

In [169]:
gc.assign_age("20")

In [170]:
gc.assign_gender("male")

In [171]:
gc.show_name()

'nirmal'

In [172]:
gc.show_age()

'20'

In [173]:
gc.show_gender()

'male'

In [ ]:
#numpy

In [174]:
import numpy as np

In [175]:
n1 = np.array([10,20,30,40,50])

In [176]:
n1

array([10, 20, 30, 40, 50])

In [177]:
type(n1)

numpy.ndarray

In [179]:
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [180]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [182]:
n1 = np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [184]:
n2 = np.zeros((2,3))
n2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [185]:
n3 = np.full((3,2),5)
n3

array([[5, 5],
       [5, 5],
       [5, 5]])

In [188]:
n4 = np.arange(10,20)
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [192]:
n5 = np.arange(8,80,8)
n5

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72])

In [193]:
n6 = np.random.randint(10,90,12)
n6

array([63, 89, 59, 57, 77, 62, 29, 41, 32, 12, 17, 66])

In [194]:
n7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n7.shape

(3, 3)

In [ ]:
#joining numpy array

In [195]:
n8 = np.array([1,2,3])
n9 = np.array([4,5,6])

In [197]:
np.vstack((n8,n9))

array([[1, 2, 3],
       [4, 5, 6]])

In [198]:
np.hstack((n8,n9))

array([1, 2, 3, 4, 5, 6])

In [199]:
np.column_stack((n8,n9))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#intersection & Difference

In [201]:
n10 = np.array([1,2,3,4,5,6])
n11 = np.array([5,6,7,8,9])

In [203]:
np.intersect1d(n10,n11)

array([5, 6])

In [204]:
np.setdiff1d(n10,n11)

array([1, 2, 3, 4])

In [205]:
np.setdiff1d(n11,n10)

array([7, 8, 9])

In [ ]:
#array mathemetics

In [206]:
n12 = np.array([10,20,30])
n13 = np.array([40,50,60,])

In [208]:
np.sum([n12,n13])

210

In [209]:
np.sum([n12,n13],axis=0)

array([50, 70, 90])

In [210]:
np.sum([n12,n13],axis=1)

array([ 60, 150])

In [211]:
n14 = np.array([40,50,60,])

In [213]:
n14=n14+1
n14

array([42, 52, 62])

In [214]:
n14=n14-1
n14

array([41, 51, 61])

In [219]:
n14=n14*2
n14

array([ 82., 102., 122.])

In [217]:
n14=n14/2
n14

array([20.5, 25.5, 30.5])

In [221]:
n15 = np.array([10,20,30,40,50,60])

In [222]:
np.mean(n15)

35.0

In [223]:
np.std(n15)

17.07825127659933

In [224]:
np.max(n15)

60

In [225]:
np.median(n15)

35.0

In [228]:
n16 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n16

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [229]:
n16[0]

array([1, 2, 3])

In [230]:
n16[2]

array([7, 8, 9])

In [233]:
n16[:,2]

array([3, 6, 9])

In [238]:
n17 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n17

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [234]:
np.transpose(n16)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [239]:
n18 = np.array([[9,8,7],[6,5,4],[3,2,1]])
n18

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [240]:
n17.dot(n18)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [241]:
n18 = np.array([10,20,30,40])

In [243]:
np.save('save_n18',n18)

In [247]:
n19 = np.load('save_n18.npy')
n19

array([10, 20, 30, 40])